Handle New Patreon Tiers
goinverse-oss/app pull request #229
Opened 2020-02-22 22:59 UTC by ericbendall

## Description
Implements: https://github.com/theliturgists/app/issues/205
* Handles both new and old patreon tiers
* Also refactors patreon selectors / reducers so that the JsonApiDataStore is used once in the reducer when the data comes in
* Also hooks up Reactotron's networking functionality 

## Motivation and Context
https://github.com/theliturgists/app/issues/205

## How Has This Been Tested?
This final version still needs to be tested. The development server seemed to be down when I was trying to run this.

Also, we should probably make unit tests for this.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-02-24 02:39 UTC, brettdh approved these changes
This is great stuff, Eric; thanks a ton. I was going to suggest you add unit tests, but since I'm going to be extracting this to a common module for reuse in the backend, I can do that if you prefer.

2020-02-24 02:39 UTC, brettdh commented on src/state/ducks/patreon/reducer.js
> +  user: null,
Add to the state shape docs above plz

...which I'm now realizing is out of date 🤦‍♂ (if you could also remove `token` from that doc, that'd be greeeeat)

2020-02-24 02:39 UTC, brettdh commented on src/state/ducks/patreon/reducer.js
> +  user: null,
Also, should `rawPayload` be listed here (and documented above)?

2020-02-24 02:39 UTC, brettdh commented on src/state/ducks/patreon/reducer.js
> +    const details = new JsonApiDataStore();
Nit: suggest calling this `store` or `data` or `datastore` instead

2020-02-24 02:39 UTC, brettdh commented on src/state/ducks/patreon/selectors.js
> +  return pledge !== null && pledge?.reward?.id !== OLD_TIER_REWARD_IDS.NON_MEMBER;
I was wondering about JS support for the optional chaining, and wondering if we were getting this via transpilation, and TIL about https://facebook.github.io/react-native/docs/javascript-environment :+1:

2020-02-24 02:39 UTC, brettdh commented on src/state/ducks/patreon/selectors.js
>  }
Any reason we don't also get these from the serialized `user` data?

2020-02-24 02:40 UTC, brettdh commented
Forgot to say - I'll pull the branch and test out the reducer changes real quick. Are you still having trouble with the staging API?

2020-02-24 02:55 UTC, brettdh requested changes

2020-02-24 02:55 UTC, brettdh commented on src/state/ducks/patreon/selectors.js
>    );
Well, damn. Turns out this doesn't work:

```
undefined is not an object (evaluating 'user.pledges.filter')
```

`user` is raw json:api data, and `user.data.relationships.pledges` is just primary documents (`type` and `id`), with no `attributes`.

I'm thinking this is reason enough to revert the commit with the reducer changes, as it's probably a pain to put all the data in the right places to make it easy to work with - and `JsonApiDataStore` seems like it makes us choose between ease of data access and serializability.

2020-02-24 02:55 UTC, brettdh commented on src/state/ducks/patreon/selectors.js
>    );
I reverted that commit locally, and while it doesn't crash anymore, it also shows the wrong rewards for my patreon account (it only shows the bonus podcast, where I'm somewhere above the new meditations tier). Will investigate further.

2020-02-24 03:11 UTC, brettdh commented on src/state/ducks/patreon/selectors.js
>    );
Ok, I pushed a commit reverting the reducer change, and a commit fixing the issue I described (spoiler: json:api IDs are strings, and constants.js stored integers).

If you want to take another stab at refactoring the data serialization out of the selector, I'm up for that, but maybe in a separate PR? I'm pretty happy with this one as it is now.

2020-02-24 03:12 UTC, brettdh commented
@ericbendall I wanted to double-check before merging this: did you intend to use your sony.com email address (which you did), or a personal one?

2020-02-24 16:05 UTC, ericbendall commented on src/state/ducks/patreon/selectors.js
>    );
Thanks for taking a stab at actually running it there. That sucks that serializing doesn't work the way we thought. Boo.

Thanks for reverting and fixes those!

2020-02-24 16:08 UTC, ericbendall commented
No, but I'll figure that out. My `~/.gitconfig` probably needs to be tweaked.

2020-02-26 03:00 UTC, brettdh approved these changes

2020-02-26 03:00 UTC, merged